# SPDX-FileCopyrightText: Copyright (c) 2024 Ferrous Systems
# SPDX-License-Identifier: MIT OR Apache-2.0

[build]
# cross-compile to this target
target = "thumbv7em-none-eabihf" # = ARM Cortex-M4 with hard-float
