# Copyright (c) 2024 Ferrous Systems
# SPDX-License-Identifier: MIT OR Apache-2.0

name: workflow-code-analysis
run-name: Run code analysis
on: [push]
jobs:
  job-clippy-demo-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install tools
        run: |
          sudo apt-get update -y && sudo apt-get -y install gcc-arm-none-eabi
      - name: Add rustup target
        run: |
          rustup target add thumbv7em-none-eabihf
      - name: Check Clippy on Demo App
        env:
          RUSTFLAGS: "-Dwarnings"
        run: |
          cd demo-app
          cargo clippy --all-features
  job-clippy-freertos-sys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install tools
        run: |
          sudo apt-get update -y && sudo apt-get -y install gcc-arm-none-eabi
      - name: Add rustup target
        run: |
          rustup target add thumbv7em-none-eabihf 
      - name: Check Clippy on freertos-sys
        env:
          RUSTFLAGS: "-Dwarnings"
        run: |
          cd freertos-sys
          cargo clippy --all-features --target=thumbv7em-none-eabihf
